const data={
    products:[
    {
      _id:'1',
      image:'/resimler/atesgömlek.jpg',
      name:'Ateşten Gömlek',
      yazar:'Halide Edip Adıvar',
      yayinevi:'Can Yayınları',
      yorum:16,
      price:26.99,
      description:'Türk edebiyatının önemli yazarlarından Halide Edip Adıvar, Kurtuluş Savaşı yıllarını Ateşten Gömlek ile günümüze taşıyor. Adıvar, Kurtuluş Savaşı mücadelesinde Mustafa Kemal Atatürk’ün yanında bizzat yer alıyor. Ateşten Gömlek, yazar tarafından tam da bu yıllarda kaleme alınmaya başlıyor. 1922 yılında ilk kez yayımlanan eser, Kurtuluş Savaşı’nı anlatan ilk roman olarak biliniyor. Eserde savaş yıllarında Anadolu’nun durumu tüm gerçekliğiyle yansıtılırken, kahramanların iç dünyasına da değiniliyor.',
      
    },
    {
      _id:'2',
      image:'/resimler/sineklibakkal.jpg',
      name:'Sinekli Bakkal',
      yazar:'Halide Edip Adıvar',
      yayinevi:'Can Yayınları',
      yorum:66,
      price:34.99,
      description:'İşlediği konu itibarıyla Osmanlı’nın son dönemlerini yakın bir gözle inceleme imkanı sunan Sinekli Bakkal, Halide Edip Adıvar’ın unutulmaz eserleri arasında yer alıyor. Dönemin siyasal, toplumsal ve kültürel yanlarını gözler önüne seren roman, aynı zamanda Doğu ve Batı’nın zıt yaşantısına eleştirel bir yorum getiriyor. Adıvar, romanında Doğu ve Batı’nın çatışmasını değil, sentezini savunuyor. Bunu da kitapta başkahraman olarak konumlandırdığı Rabia isimli karakter ile gösteriyor.II. Abdülhamid’in himayesindeki İstanbul’a daha yakından bakacağınız bu eser ile Jön Türkleri de tanıyacak, sürgünlerin ardında bıraktığı yıkımlara şahit olacaksınız. Dönem romanlarını okumayı sevenler için ayrı bir öneme sahip olan Halide Edip Adıvar, en çok satan eseri Sinekli Bakkal ile de bu başarısını ispatlıyor.',
    },
    {
      _id:'3',
      image:'/resimler/icimizdeki-seytan.jpg',
      name:'İçimizdeki Şeytan',
      yazar:'Sabahattin Ali',
      yayinevi:'Yapı Kredi Yayınları',
      yorum:22,
      price:15.99,
      description:'"İsteyip istemedeğimi doğru dürüst bilmediğim, fakat neticede aleyhime çıkarsa istemediğimi iddia ettiğim bu nevi söz ve fiillerimin daimi bir mesulünü bulmuştum: Buna içimdeki şeytan diyordum, müdafaasını üzerime almaktan korktuğum bütün hareketlerimi ona yüklüyor ve kendi suratıma tüküreceğim yerde, haksızlığa, tesadüfün cilvesine uğramış bir mazlum gibi nefsimi şefkat ve ihtimama layık görüyordum. Halbuki ne şeytanı azizim, ne şeytanı? Bu bizim gururumuzun, salaklığımızın uydurması.."Bu romanında, toplumsal gündemin kişilikler üzerindeki baskısını ve güçsüz insanın "kapana kısılmışlığını" gösteriyor Sabahattin Ali. Aydın geçinenlerin karanlığına, "insanın içindeki şeytan"a keskin bir bakış.',
    },
    {
      _id:'4',
      image:'/resimler/madonna.jpg',
      name:'Kürk Mantolu Madonna',
      yazar:'Sabattin Ali',
      yayinevi:'Yapı Kredi Yayınları',
      yorum:56,
      price:19.99,
      description:'Konusu ile adından sıkça söz ettiren eser, Türk edebiyatının da en önemli romanları arasında gösteriliyor. Psikolojik bir anlatı olarak da ifade edebileceğimiz roman aslında üç ana tema etrafında şekilleniyor: Aşk, yalnızlık ve yabancılaşma. Kürk Mantolu Madonna, daha çok bir aşk hikayesi olarak görünse de romanda aslında bir insanın yalnızlaşma sürecine ve giderek topluma yabancılaşmasına şahit oluyoruz. Psikolojik tahliller çerçevesinde bu yabancılaşma ve yalnızlık duygusunu Sabahattin Ali o kadar iyi anlatıyor ki, okurken bize bu hisleri adeta yaşıyormuşçasına hissettiriyor.', 
    },
    {
      _id:'5',
      image:'/resimler/vebageceleri.jpg',
      name:'Veba Geceleri',
      yazar:'Orhan Pamuk',
      yayinevi:'Yapı Kredi Yayınları',
      yorum:86,
      price:24.99,
      description:'1901 baharında Osmanlı İmparatorluğu’nun 29. vilayeti Minger Adası’nda veba salgını baş gösterince Sultan Abdülhamit önce Sağlık Başmüfettişi kimyager Bonkowski Paşa’yı, onun arkasından da genç ve başarılı Doktor Nuri’yi salgını durdurması için adaya gönderir. Padişah kısa bir süre önce genç doktoru, sarayda hapis hayatı yaşattığı ağabeyi önceki padişah V. Murat’ın kızı Pakize Sultan ile evlendirmiştir ve Pakize Sultan da bu yolculukta kocasına eşlik etmektedir. Adada ise genç ve milliyetçi Osmanlı subayı Kolağası Kâmil, onun âşık olduğu adalı Zeynep ve her şeye yetişmeye çalışan Vali Sami Paşa ile güzel sevgilisi Marika vardır. Karantina yasaklarına itaat edilmesi için çaba harcayan bu insanların vebayla, adadaki geleneklerle ve sonunda birbirleriyle ve ölüm tehditleriyle savaşının ve yaşadıkları aşkların hikâyesidir.',
    },
    {
      _id:'6',
      image:'/resimler/safahat.jpg',
      name:'Safahat',
      yazar:'Mehmet Akif Ersoy',
      yayinevi:'Dünya Bizim Kitaplığı',
      yorum:116,
      price:19.99,
      description:'Halkın içinden yükselmiş, ama halkın içinde kalmış bir şair; kendi milleti kadar, Doğu’yu ve Batı’yı dili, edebiyatı ve müziği ile bilen bir aydın; Veterinerlik Fakültesi’nin ilk öğrencisi ve birincisi; İstanbul Boğazı’nı yüzerek geçen, at binen, gülle atan ve güreşen bir sporcu; şehirde kapanıp kalmamış, Anadolu köylerindeki ahırlarda hayvan tedavi etmiş, gerçekleri yaşamış ve -neye mal olursa olsun- hep gerçekleri söylemiş bir adam; milletiyle birlikte savaşı, acıyı, yenilgiyi ve zaferi gören gözleri, her daim yaşlı duygulu bir insan, bir şair...Bu adam, “İstiklâl Marşı”mızın yazarı Mehmed Âkif Ersoy’dur.O, bütün hayatı, ahlâkı, kişiliği, davranış ve düşünceleriyle birlikte, kendimiz ve çocuklarımız için, hiç çekinmeden, “İşte tam bir örnek!” diyebileceğimiz, bir millî kahramandır.Onun eseri olan “Safahat”, bu milletin çağdaş destanıdır.Milletimizin bin yılda kıvâma ermiş olan ruh ve fikir olgunluğu, inanç ve ahlâk sağlamlığı, cesareti ve kahramanlığı -elbette kusurları ve tedavi çareleriyle birlikte- bu destanda dile getirilmiştir.“Kendisi”ni ve milletini öğrenmek isteyen genç aydınlar, onu okuyacak ve anladıkları kadar bu “millet”ten olacaklardır.Mehmed Âkif gibi bir evlâda ve “Safahat” gibi bir esere sahip olmak, bir millet için, büyük bir şans ve büyük bir mutluluktur...',
    },
    {
      _id:'7',
      image:'/resimler/intibah.jpg',
      name:'İntibah',
      yazar:'Namık Kemal',
      yayinevi:'Bilgi Kültür Sanat',
      yorum:55,
      price:14.99,
      description:"Namık Kemal, İntibah romanını 1873-1876 yılları arasında sürgünde bulunduğu Magosa'da kaleme almış ve romana Son Pişmanlık adını vermiştir. Hem sanatçı hem de dava adamı olan Namık Kemal, İntibah romanını tiyatrolarında olduğu gibi eğlendirirken eğitmek amacıyla yazmıştır.Varlıklı bir ailenin çocuğu olan Ali Bey, iyi bir eğitim ve öğrenim görmüş bir gençtir. Yalnız hayat tecrübesi yoktur. O devrin seçkin gezinti yerlerinden biri olan Çamlıca'da dolaşırken Mehpeyker'le tanışır. Genç adam, ilk karşılaşmada ilgi duyduğu bu kadını derin bir aşkla sever. İntibah; Ali Bey'i her şeyini, sağlığını, sevdiği kadını, servetini, onurunu ve annesine olan saygısını kaybetmiş zavallı bir insan yapan ve Son pişmanlık fayda vermez dedirten felaketlerin anlatıldığı bir romandır.",
    },
    {
      _id:'8',
      image:'/resimler/serenad.jpg',
      name:'Serenad',
      yazar:'Zülfü Livaneli',
      yayinevi:'İnkılap Kitabevi',
      yorum:189,
      price:39.99,
      description:'“Ömür boyu süren bir aşk üzerine harika bir kitap.” Frankfurter Allgemeiner Zeitung “Klasikler gibi okunan bir senfoni.” Neue Zurcher Zeitung“Serenad, Türk edebiyatında kalıcılaşacağı gibi, dünya edebiyatında da önemli bir yapıt olarak yerini alacaktır.” Prof. Dr. Onur Bilge Kula“Yılın Favori Kitabı” Boston Globe Okurları - “Yılın En İyi Kitabı” PopMatters2. Dünya Savaşı sırasında batırılan bir mülteci gemisinin hikâyesine dayanan bu etkileyici romanda, Almanya doğumlu yaşlı bir profesör, sevgili karısını en son gördüğü yeri ziyaret etmek için Amerika’dan İstanbul’a gelir. Maya Duran, İstanbul Üniversitesi’ndeki zorlu işi ile genç bir oğul yetiştirmenin zorluklarını dengelemeye çalışan bekar bir annedir. Maya, üniversitenin daveti üzerine gelen Prof. Maximilian Wagner’i ağırlamakla görevlendirilir. Başta, etrafında gelişen olaylara ve Profesör’e karşı kayıtsız görünse de altmış yıllık bu esrarengiz hikâye sayesinde kendi kökleriyle ilgili üstü kapatılan pek çok karanlık gerçeği yavaş yavaş öğrenir.Yaklaşık 800 Yahudi mültecinin kendilerini Filistin’e taşıyan geminin Türkiye kıyılarında torpidolanması sonucu hayatını kaybettiği 1942 Struma felaketinden esinlenen Serenad, hem dokunaklı bir aşk hikâyesi hem de krizdeki insan ilişkilerinin gücünün unutulmaz bir anlatısı.Pek çok dile çevrilen, özellikle İngilizce edisyonuyla dünyanın dört bir yanında okurlarıyla buluşan Serenad, müzik, edebiyat ve yakın tarihin iç içe geçtiği bir Livaneli romanı.',   
    },
    {
      _id:'9',
      image:'/resimler/kayiptanrilarülkesi.jpg',
      name:'Kayıp Tanrılar Ülkesi',
      yazar:'Ahmet Ümit',
      yayinevi:'Yapı Kredi Yayınları',
      yorum:45,
      price:24.99,
      description:'Ahmet Ümit’ten polisiyeyi arkeoloji ve mitolojiyle harmanlayan usta işi bir roman. Berlin Emniyet Müdürlüğü’nün cevval başkomiseri Yıldız Karasu ve yardımcısı Tobias Becker, göçmenlerin, işgal evlerinin ve sokak sanatçılarının renklendirdiği Berlin sokaklarından Bergama’ya uzanan bir macerada, hayatı ve insanları yok etmeye muktedir sırların peşinde bir seri cinayetler dizisini çözmeye çalışıyor. Soruşturmanın Türkiye ayağında sürpriz bir ismin olaya dahil olmasıyla heyecanın dozu gitgide artıyor.Kayıp Tanrılar Ülkesi, Zeus Altarı ve Pergamon Tapınağı’nın gölgesinde mitlere günümüzde yeniden hayat verirken, suçun çağlar ve kültürler boyu değişmeyen doğasını bir tokat gibi yüzümüze çarpıyor.O yüzden unuttuk dediğiniz yerden başlayacağım. Unutmanın bedelini ödeyecek unutanlar. Cezaların en şiddetlisiyle ödüllendirilecek saygısızlık yapanlar, kalbi yerinden çıkarılacak beni kalbinden çıkaranların, yüzlerinin derisi yüzülecek benden yüz çevirenlerin…”', 
    },
    {
      _id:'10',
      image:'/resimler/sefiller.jpg',
      name:'Sefiller',
      yazar:'Victor Hugo',
      yayinevi:'İskele Yayınları',
      yorum:186,
      price:44.99,
      description:"Jan Valjan, aç ailesini doyurmak için ekmek çaldığından, bir kadırgada kürek çekmeye mahkûm edilmiştir. Kaçma girişiminde bulunduğu için de mahkumiyet süresi on dokuz seneye çıkarılır ve 1815'te serbest bırakılır. Hapisten çıkınca, mahkûm olduğunu gösteren belge yüzünden herkes ona kötü davranır. Bir piskopos onu evine alır, o ise evin gümüş takımlarını çalarken yakalanır. Piskopos şikayetçi olmaz, üstelik ona iki de gümüş şamdan hediye eder. Onlardan elde edeceği parayı namuslu adam olma yolunda harcamasını ister. Bu son olay, Jan Valjan için bir dönüm noktası olur. Madeleine adıyla iş hayatına atılır, zengin olur ve belediye başkanı seçilir. Fantin adında, düşmüş fakat ruhça temiz bir kadını polis şefi Javert'in elinden kurtarır. Javert, birdenbire ortaya çıkan, kısa sürede zengin olan ve herkesin 'Baba' dediği Madeleine'in kim olduğunu merak eden ve araştırmaya başlar.",  
    },
    {
      _id:'11',
      image:'/resimler/beyaz-dis.jpg',
      name:'Beyaz Diş',
      yazar:'Jack London',
      yayinevi:'Can Yayınları',
      yorum:214,
      price:14.99,
      description:'Vahşi kapitalizmin “altına hücum” dönemini konu alan yüzlerce eserin çoğu, altın arayıcılarının kişisel öykülerini yüzeysel bir yaklaşımla anlatır. Farklı bakış açısıyla diğerlerinden ayrılan Charlie Chaplin’in Altına Hücum filmi dışında, konuyu değişik bir biçimde irdeleyerek insanı evrensel boyutta sorgulayan en önemli eserlerden biri, Jack London’ın Beyaz Diş adlı romanıdır. Dünya görüşünü, “Köpeğe kemik atmak hayırseverlik değildir. Hayırseverlik, kendin de en az köpek kadar açken kemiği köpekle paylaşmaktır,” diye özetleyen London, Beyaz Diş’te Kuzey’in karlarla kaplı bölgelerinde sürdürülen yaşam kavgasını, soğuk, açlık ve hayatta kalma mücadelesini insanların değil, aynı koşulları onlarla paylaşan hayvanların açısından aktarır.Beyaz Diş, damarlarında hem kurt hem de köpek kanı taşıyan bir kurt kırmasıdır. Ana babası dışında kendi türünden canlıları hiç tanımadan bir mağarada yaşarken günün birinde dışarıdaki gerçek dünyayla yüz yüze gelir. Çok farklı görünen, çok farklı kuralları ve düzeni olan bu yerden, dünyayı ve yaşamı keşfetmeye başlar. Kurdun köpeğe dönüşümü, koşulların insanlar için olduğu gibi hayvanlar için de belirleyici olduğunu gözler önüne serer.',  
    },
    {
      _id:'12',
      image:'/resimler/beyaz-zambak.jpg',
      name:'Beyaz Zambaklar Ülkesinde',
      yazar:'Grigoriy Petrov',
      yayinevi:'İndigo Kitap',
      yorum:259,
      price:14.99,
      description:"Eski bir papaz, ayrıca yayıncı ve gazeteci olan Grigoriy Petrov, Finlandiya'ya ve Johan Wilhelm Snelman'a adadığı bu ölümsüz eserini, başka ülkelere ama özellikle Rusya'ya örnek teşkil etsin diye kaleme almıştır. Sonuçta yoksul, kurak ve az nüfuslu Finlandiya hayat yaratıcıları olarak adlandırılan yurttaşlarının el ele vermesiyle adeta küllerinden doğmuş; din, dil, ırk, eğitim, aile hayatı ve yönetim gibi konularda son sürat gelişmiş ve bu sayede diğer bütün ülkeleri geride bırakmayı başarmıştır. Asıl Petrov'un ölümünden sonra yankı bulan Beyaz Zambaklar Ülkesinde, özellikle Bulgaristan'da ve Türkiye'de sayısız baskı yapmıştır, öyle ki okumaya başladığı andan itibaren kitaba hayran kalan Mustafa Kemal Atatürk bu ölümsüz eserin okulların müfredatına konmasını istemiştir. İsveç'in hâkimiyetinden çıkarak görece daha ılıman Rus egemenliği altına giren Finlandiya halkının omuz omuza vererek kendi ulusal kimliklerini bulmaya çalışmalarına tanık olacak ve bu halkın, ülkesini daha ileriye taşıyacak nitelikte yeniliklere imza atan şahsiyetleriyle tanışacaksınız.",   
    },
    {
      _id:'13',
      image:'/resimler/farelerveinsanlar.jpg',
      name:'Fareler Ve İnsanlar',
      yazar:'John Steinbeck',
      yayinevi:'Sel Yayınları',
      yorum:76,
      price:22.99,
      description:'Nobel ödüllü yazar John Steinbeck’in ilk kez 1937 yılında yayınlanan eseri; çiftlikten çiftliğe dolaşarak çalışan iki yakın arkadaşın başından geçen maceraları ve onların hayallerine sıkı sıkıya olan bağlılığını konu ediniyor. Kendisi de bir dönem gezici çiftlik işçiliği yapmış olan John Steinback’in hayatından da izler taşıyan roman, realist yaklaşımı ile dikkat çekiyor. Gerçeğe yakın bir dil ile kurgulanan eser, oldukça sürükleyici ve etkileyici anlatımı ile günümüzde hala en çok okunan kitaplar arasında bulunuyor.',
    },
    {
      _id:'14',
      image:'/resimler/gerceklerkanitister.jpg',
      name:'Gerçekler Kanıt İster',
      yazar:'Sir Arthur Conan Doyle',
      yayinevi:'Martı Yayınları',
      yorum:162,
      price:34.99,
      description:'Ünlü dedektif Sherlock Holmes, heyecanlı hikâyeleriyle sizi etkilemeye devam ediyor. Toplam 56 hikâyenin yer aldığı serinin dördüncü kitabı Gerçekler Kanıt İsteri okurken her hikâyenin sonunda Sherlock Holmesun akıl dolu yöntemleri karşısında şaşkına döneceksiniz.Ben dâhi değilim, sadece önyargısız bir şekilde gerçeklerin beni götürdüğü yere gitmeyi öğrendim. Sherlock Holmes'
    },
    {
      _id:'15',
      image:'/resimler/kelebekevi.jpg',
      name:'Kelebek Evi',
      yazar:'Katrine Engberg',
      yayinevi:'The Roman',
      yorum:47,
      price:36.99,
      description:'Uluslararası çok satan yazar Katrine Engberg, 25 farklı dile çevrilen romanı Kiracı’dan sonra Kopenhag serisine Kelebek Evi ile devam ediyor.Kopenhag’da bir çeşmenin içinde ölü bir kadının çıplak bedeni bulunur. Fakat polis şimdiye kadar hiç görmediği bir öldürme yöntemiyle karşı karşıyadır. Çünkü kadının vücudunda simetrik kesikler vardır ve vücudundaki bütün kan tamamen boşaltılmıştır; tüm bunlar onlara bir şey mi anlatmaktadır? Dedektif Jeppe Korner şehri meraklandıran bu gizemli davanın soruşturmasına öncülük eder; cevapları aramak için sokak sokak dolaşırken, doğum izninde olan ortağı Anette Werner ise serbest dedektiflik yapmaya karar verir.Soruşturma tekinsiz köşelere doğru ilerlerken Dedektif Jeppe Korner ve Anette Werner’in keşfedecekleri şeyler kanlarını donduracaktır. Ve bu arada, bir sonraki cinayete kadar da zaman hızla akmaktadır…“Tatmin edici. Bu kitap polisiye hayranlarını memnun edecek.”- Kirkus Reviews“Kelebek Evi özgün ve sürükleyici bir eser. Romanları çok satanlar listesinde yer alan Katrine Engberg, dikkat edilmesi gereken bir isim.” - Sunday Times',
    },
    {
      _id:'16',
      image:'/resimler/satranc.jpg',
      name:'Satranç',
      yazar:'Stefan Zweig',
      yayinevi:'İş Bankası Kültür Yayınları',
      yorum:124,
      price:44.99,
      description:'Kitap, eserde adı belirtilmeyen baş karakterin New York’tan Buenos Aires’e giden bir gemiye binmesiyle başlıyor. Öykü boyunca anlatıcılık rolünü üstlenen baş karakter, dünya satranç şampiyonu Mirko Czentovic’in de gemide olduğunu öğreniyor. Onunla bir maç yapmak istiyor ancak Czentovic buna hiç de istekli görünmüyor,Bunun üzerine baş karakter, onun dikkatini çekebilmek için McConnor adlı bir adamla satranç masasına oturuyor. Oyun yine de Czentovic’in dikkatini çekmeyi başaramıyor. En sonunda McConnor, Czentovic’e para karşılığı maç teklif ediyor. Ancak bu şekilde ikna edilebilen Czentovic, böylelikle masadaki yerini alıyor.McConnor kaybedeceği bir hamle yapmak üzereyken, yabancı bir ses duruma müdahale ediyor. Kitapta Dr. B. adıyla verilen sesin sahibi, satrançtaki hünerini Czentovic’ten apayrı bir hikayeye borçlu olarak anlatılıyor. Kitabın gelişme bölümünün doruklarında, ikili arasında kıyasıya bir rekabet gelişiyor. Öyle ki iş artık, satrançtan ziyade savaşın acı bir temsiline dönüşüyor.',  
    },
    {
      _id:'17',
      image:'/resimler/seytaniuyandirma.jpg',
      name:'Şeytanı Uyandırma',
      yazar:'John Verdon',
      yayinevi:'Koridor Yayıncılık',
      yorum:169,
      price:54.99,
      description:'Asla o karanlık odaya girme.Sabaha çıkmak istiyorsan şeytanı uyandırma.Hiçbir cinayet kusursuz değildir. Özellikle Dahi Dedektif Dave Gurney bir olaya müdahil olup hiç kimsenin göremediği detayları ortaya çıkardığında, çıkışı olmadığı düşünülen labirentin çıkışını ustalıkla bulduğunda...Gurney, bir seri katil üzerine belgesel hazırlayan genç bir kıza danışmanlık yapmayı kabul eder. On yıl önce yaşanan bu olaylarda kurbanların hepsi keskin bir nişancı tarafından zifiri karanlıkta, pahalı Mercedes arabalarını kullanırken, aynı açıdan ve noktadan kusursuz biçimde vurulmuş ve bedenlerinin yanına birer oyuncak hayvan bırakılmıştır. Asla aydınlatılamayan bu cinayetlerin üstüne bir perde çekilmiştir ve kimse bu perdeyi kaldırabilecek kadar cesaretli değildir. Tek bir kişi dışında.Gurneyin kimseye izini belli etmeyecek kadar dahiyane bir plan yapmış olan bu caniyle oynayabileceği tek bir oyun vardır. Ölüm oyunu: Kendini hedef göster, o sana gelsin.',  
    },
    {
      _id:'18',
      image:'/resimler/simyaci.jpg',
      name:'Simyacı',
      yazar:'Paulo Coelho',
      yayinevi:'Can Yayınları',
      yorum:354,
      price:34.99,
      description:'Dünya edebiyatının fenomenleri arasında yer alan Simyacı, yayımlandığı günden bugüne pek çok hayata dokunmaya devam ediyor. Brezilyalı yazar Paulo Coelho tarafından 1988 yılında yayımlanan eser, Doğu ve Batı dünyasına aynı pencereden ışık tutuyor. Coelho’nun Mesnevi’deki bir kıssadan hareketle kaleme aldığı Simyacı, macera dolu öyküsü ve felsefi yönüyle başucu kitabınız olmaya aday! Etkileyici hikayesi, sade anlatımı ve derinliğiyle Simyacı, dünya klasiklerinin en sevilen eserlerinden biri. Yayımlandıktan kısa süre sonra 42 ülkede basılan ve 26 dile çevrilen eser, 1996’dan günümüze Türkiye’de de en çok okunan romanlar arasındaki yerini koruyor. Eğer hem bir macera tutkunu hem de felsefe meraklısıysanız Simyacı, sizi de etkisi altına alacak. Simyacı, Santiago adındaki Endülüslü bir çobanın İspanya’dan başlayıp Mısır’da sona eren yolculuğunu konu ediniyor. Gördüğü bir rüya üzerine sahip olduğu her şeyi ardında bırakan Santiago’nun bu serüveni, onu düşlerine kavuşturduğu kadar hayatın hakikatine de ulaştırıyor. Simyacı’nın sayfalarını çevirdikçe siz de Santiago’yla birlikte kendi içinize doğru bir yolculuğa çıkacaksınız.',     
    },
    {
      _id:'19',
      image:'/resimler/yabanci.jpg',
      name:'Yabancı',
      yazar:'Albert Camus',
      yayinevi:'Can Yayınları',
      yorum:174,
      price:49.99,
      description:'Tüm zamanların en tanınmış yazarlarından biri olan Albert Camus, en fazla ses getiren “Yabancı” adlı romanı ile okuyucularla buluşuyor. Camus’nün en fazla dile çevirilen ve tüm dünyada en çok satan kitabı olan “Yabancı”, bir yandan da okuyucuyu varoluşculuk akımıyla buluşturuyor. Ele aldığı karakterin düşünce yapısından anladığımız bu akım ile yazar dünyaya tek düze bir gözden bakıyor ve olayları tek düze bir göz ile yorumluyor. Kimilerine göre son derece duygusuz olarak nitelendirilen kahramanın davranışları, aslında kendi içerisinde derin anlamlar barındırıyor.Albert Camus’nün nobel edebiyat ödüllü bu eseri ile sizi de hayata karşı derin düşüncelere dalacağınız bir yolculuk bekliyor. Önce “İnsan bu kadar vurdumduymaz olur mu?” diye düşünecek, ardından insanı buna iten nedenler hakkında bir iç sorgulamaya varacaksınız. Kütüphanenizden eksik etmemeniz gereken bir roman daha Albert Camus’nün güçlü kalemiyle karşınızda…',    
    },
    {
      _id:'20',
      image:'/resimler/yüzyillikyalnizlik.jpg',
      name:'Yüzyıllık Yalnızlık',
      yazar:'Gabriel Garcia Marquez',
      yayinevi:'Can Yayınları',
      yorum:187,
      price:54.99,
      description:'Nobel Ödüllü Kolombiyalı Yazar Gabriel Garcia Marquez’in Yüzyıllık Yalnızlık romanı, gerçeklik kavramına kattığı olağandışı boyutla, yayımlandığı 1967’den bugüne edebiyat dünyasındaki değerini korumaya devam ediyor. Marquez’in 1982 yılında Nobel Edebiyat Ödülü’nü almasını sağlayan roman, edebiyat dünyasına yazarın kazandırdığı “büyülü gerçekçilik” akımının en ihtişamlı örneğini oluşturuyor.Marquez’in kendi hayatından yola çıkarak kaleme aldığı Yüzyıllık Yalnızlık, gerçekçi anlatımının yanı sıra fantastik kurgusuyla dünya edebiyatının kültleri arasında yer alıyor. Yazarın iki yıldan daha kısa bir sürede tamamladığını dile getirdiği eser, kendisinin de ifadesiyle 15-16 yıllık düşünsel birikiminin eseri olarak onun çocukluk yıllarının sanatsal bir anlatımı niteliğini taşıyor.',   
    },
    ]
    }
    export default data